dependencies:
- name: redis
  version: 8.0.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled, redis.embeddedRedis
- name: mariadb
  version: 1.0.5
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mysql.embeddedMaria
