version: 2
jobs:
  lint:
    docker:
      - image: quay.io/deis/go-dev:v1.2.0
    steps:
      # TODO: save the checked-out code in a working directory.
      # do the same with the installed helm and az binaries
      - checkout
      - run:
          name: Install Basic Utilities
          command: ./install-base-prereqs.sh
          working_directory: scripts
      - run:
          name: Install Helm
          command: ./install-helm.sh
          working_directory: scripts
      - run:
          name: Helm Lint
          command: ./helm-lint.sh
          working_directory: scripts
  # this step tests the install script for the Azure CLI
  test-install-az-cli:
    docker:
      - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Install Basic Utilities
          command: ./install-base-prereqs.sh
          working_directory: scripts
      - run:
          name: Install the Azure CLI
          command: ./install-azure-cli.sh
          working_directory: scripts
  helm-sync:
    docker:
      - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Install Basic Utilities
          command: ./install-base-prereqs.sh
          working_directory: scripts
      - run:
          name: Install Helm
          command: ./install-helm.sh
          working_directory: scripts
      - run:
          name: Install Azure CLI 2.0
          command: ./install-azure-cli.sh
          working_directory: scripts
      - run:
          name: Sync Helm Repository
          command: ./helm-repo-sync.sh
          working_directory: scripts
          branches:
            only:
              - master
workflows:
  version: 2
  test-pr:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              ignore: master
      - lint:
          requires:
            - hold
          filters:
            branches:
              ignore: master
      - test-install-az-cli:
          requires:
            - hold
          filters:
            branches:
              ignore: master
  test-and-deploy-master:
    jobs:
      - lint:
          filters:
            branches:
              only: master
      - helm-sync:
          requires:
            - lint
          filters:
            branches:
              only: master
