version: 2
jobs:
  lint:
    docker:
      - image: quay.io/deis/helm-chart-publishing-tools:v0.1.0
    working_directory: /charts
    steps:
      - checkout
      - run:
          name: Helm Lint
          command: ./helm-lint.sh
          working_directory: scripts
  helm-sync:
    docker:
      - image: quay.io/deis/helm-chart-publishing-tools:v0.1.0
    working_directory: /charts
    steps:
      - checkout
      - run:
          name: Sync Helm Repository
          command: ./helm-repo-sync.sh
          working_directory: scripts
          branches:
            only:
              - master
workflows:
  version: 2
  test-pr:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              ignore: master
      - lint:
          requires:
            - hold
          filters:
            branches:
              ignore: master
  test-and-deploy-master:
    jobs:
      - lint:
          filters:
            branches:
              only: master
      - helm-sync:
          requires:
            - lint
          filters:
            branches:
              only: master
