apiVersion: v1
kind: Secret
metadata:
  name: asb-jimz-testing-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJaR1ZwY3l0d2RXeHNYMjl1YkhrNldFcEpNMHBET1U4eE4wUTNUVEEyTnpWVlRVc3lTek5XTWs5YVdWZENVRUZSVkVaTFVsQldRVUZXU0ZNeFdscE1UREZXVmpCSlRVNVlNMGxCT0V0WVZnPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
