{{- if not .Values.mysql.embeddedMaria }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ template "fullname" . }}-mysql-instance
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterServiceClassExternalName: azure-mysqldb
  clusterServicePlanExternalName: {{ .Values.mysql.azure.servicePlan }}
  parameters:
    location: {{ .Values.mysql.azure.location }}
    resourceGroup: {{ .Release.Namespace }}
    sslEnforcement: disabled
    firewallStartIPAddress: 0.0.0.0
    firewallEndIPAddress: 255.255.255.255
{{- end }}
