{{- if include "ghost.host" . -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "ghost.fullname" . }}
  labels:
    app: {{ template "ghost.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "ghost.fullname" . }}
    spec:
      initContainers:
      - name: volume-permissions
        image: "{{ .Values.volumePermissions.image.name }}:{{ .Values.volumePermissions.image.tag }}"
        imagePullPolicy: {{ default "" .Values.volumePermissions.image.pullPolicy | quote }}
        command: ['sh', '-c', 'chmod -R g+rwX /bitnami']
        volumeMounts:
        - mountPath: /bitnami
          name: ghost-data
      containers:
      - name: {{ template "ghost.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        {{- if .Values.mysql.embeddedMaria }}
        - name: MARIADB_HOST
          value: {{ template "ghost.mariadb.fullname" . }}
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: GHOST_DATABASE_NAME
          value: {{ default "" .Values.mariadb.mariadbDatabase | quote }}
        - name: GHOST_DATABASE_USER
          value: {{ default "" .Values.mariadb.mariadbUser | quote }}
        - name: GHOST_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.mariadb.fullname" . }}
              key: mariadb-password
        {{- else }}
        - name: MARIADB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}-mysql-secret
              key: host
        - name: MARIADB_PORT_NUMBER
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}-mysql-secret
              key: port
        - name: GHOST_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}-mysql-secret
              key: database
        - name: GHOST_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}-mysql-secret
              key: username
        - name: GHOST_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}-mysql-secret
              key: password
        {{- end }}
        - name: GHOST_HOST
          value: {{ include "ghost.host" . | quote }}
        - name: GHOST_PORT_NUMBER
          value: {{ default "80" .Values.ghostPort | quote }}
        - name: GHOST_USERNAME
          value: {{ default "" .Values.ghostUsername | quote }}
        - name: GHOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}
              key: ghost-password
        - name: GHOST_EMAIL
          value: {{ default "" .Values.ghostEmail | quote }}
        - name: BLOG_TITLE
          value: {{ default "" .Values.ghostBlogTitle | quote }}
        - name: SMTP_HOST
          value: {{ default "" .Values.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ default "" .Values.smtpPort | quote }}
        - name: SMTP_USER
          value: {{ default "" .Values.smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}
              key: smtp-password
        - name: SMTP_SERVICE
          value: {{ default "" .Values.smtpService | quote }}
        ports:
        - name: http
          containerPort: {{ default "80" .Values.ghostPort }}
        livenessProbe:
          httpGet:
            path: /ghost
            port: http
            httpHeaders:
            - name: Host
              value: {{ include "ghost.host" . | quote }}
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /ghost
            port: http
            httpHeaders:
            - name: Host
              value: {{ include "ghost.host" . | quote }}
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: ghost-data
          mountPath: /bitnami/ghost
      volumes:
      - name: ghost-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "ghost.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
{{- end -}}
