{{- if not .Values.mysql.embeddedMaria }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ template "ghost.fullname" . }}-mysql-instance
  labels:
    app: {{ template "ghost.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterServiceClassExternalName: azure-mysqldb
  clusterServicePlanExternalName: standard800
  parameters:
    location: eastus
    resourceGroup: {{ .Release.Namespace }}
    sslEnforcement: disabled
{{- end }}
